# 配置 Dependabot 自动更新依赖
version: 2
updates:
  # 配置 GitHub Actions 的更新规则
  - package-ecosystem: "github-actions"
    directory: "/"  # 工作流文件通常在 .github/workflows 目录
    schedule:
      interval: "weekly"  # 每周检查一次更新
    # 只更新 patch 级别版本
    versioning-strategy: "pin"

  # 配置 npm 的更新规则
  - package-ecosystem: "npm"
    directory: "/"  # package.json所在目录
    schedule:
      interval: "weekly"
    # 只接受 patch 级别更新
    versioning-strategy: "pin"